#############################################################################
# Makefile for building: MO
# Generated by qmake (2.01a) (Qt 4.6.2) on: ?? ????. 15 19:04:06 2010
# Project:  MO.pro
# Template: app
# Command: /home/mik/qtsdk-2010.02/qt/bin/qmake -spec ../qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MO.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I../qtsdk-2010.02/qt/mkspecs/linux-g++-64 -I. -I../qtsdk-2010.02/qt/include/QtCore -I../qtsdk-2010.02/qt/include/QtGui -I../qtsdk-2010.02/qt/include/QtWebKit -I../qtsdk-2010.02/qt/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-rpath,/home/mik/qtsdk-2010.02/qt/lib
LIBS          = $(SUBLIBS)  -L/home/mik/qtsdk-2010.02/qt/lib -lQtWebKit -L/home/mik/qtsdk-2010.02/qt/lib -L/usr/X11R6/lib64 -lphonon -L/home/berlin/dev/qt-4.6.2-opensource-shipping/this_path_is_supposed_to_be_very_long_hopefully_this_is_long_enough/qt/lib -lQtDBus -lQtXml -lQtXmlPatterns -lQtNetwork -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /home/mik/qtsdk-2010.02/qt/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		widget.cpp \
		equation.cpp \
		function.cpp \
		inputWidget.cpp \
		STable.cpp moc_widget.cpp \
		moc_equation.cpp \
		moc_function.cpp \
		moc_inputWidget.cpp
OBJECTS       = main.o \
		widget.o \
		equation.o \
		function.o \
		inputWidget.o \
		STable.o \
		moc_widget.o \
		moc_equation.o \
		moc_function.o \
		moc_inputWidget.o
DIST          = ../qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		MO.pro
QMAKE_TARGET  = MO
DESTDIR       = 
TARGET        = MO

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: MO.pro  ../qtsdk-2010.02/qt/mkspecs/linux-g++-64/qmake.conf ../qtsdk-2010.02/qt/mkspecs/common/g++.conf \
		../qtsdk-2010.02/qt/mkspecs/common/unix.conf \
		../qtsdk-2010.02/qt/mkspecs/common/linux.conf \
		../qtsdk-2010.02/qt/mkspecs/qconfig.pri \
		../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf \
		../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf \
		../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf \
		../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf \
		../qtsdk-2010.02/qt/mkspecs/features/debug.prf \
		../qtsdk-2010.02/qt/mkspecs/features/default_post.prf \
		../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf \
		../qtsdk-2010.02/qt/mkspecs/features/qt.prf \
		../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf \
		../qtsdk-2010.02/qt/mkspecs/features/moc.prf \
		../qtsdk-2010.02/qt/mkspecs/features/resources.prf \
		../qtsdk-2010.02/qt/mkspecs/features/uic.prf \
		../qtsdk-2010.02/qt/mkspecs/features/yacc.prf \
		../qtsdk-2010.02/qt/mkspecs/features/lex.prf \
		../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf \
		/home/mik/qtsdk-2010.02/qt/lib/libQtWebKit.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libphonon.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtDBus.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtXml.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtCore.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtGui.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtXmlPatterns.prl \
		/home/mik/qtsdk-2010.02/qt/lib/libQtNetwork.prl
	$(QMAKE) -spec ../qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MO.pro
../qtsdk-2010.02/qt/mkspecs/common/g++.conf:
../qtsdk-2010.02/qt/mkspecs/common/unix.conf:
../qtsdk-2010.02/qt/mkspecs/common/linux.conf:
../qtsdk-2010.02/qt/mkspecs/qconfig.pri:
../qtsdk-2010.02/qt/mkspecs/features/qt_functions.prf:
../qtsdk-2010.02/qt/mkspecs/features/qt_config.prf:
../qtsdk-2010.02/qt/mkspecs/features/exclusive_builds.prf:
../qtsdk-2010.02/qt/mkspecs/features/default_pre.prf:
../qtsdk-2010.02/qt/mkspecs/features/debug.prf:
../qtsdk-2010.02/qt/mkspecs/features/default_post.prf:
../qtsdk-2010.02/qt/mkspecs/features/warn_on.prf:
../qtsdk-2010.02/qt/mkspecs/features/qt.prf:
../qtsdk-2010.02/qt/mkspecs/features/unix/thread.prf:
../qtsdk-2010.02/qt/mkspecs/features/moc.prf:
../qtsdk-2010.02/qt/mkspecs/features/resources.prf:
../qtsdk-2010.02/qt/mkspecs/features/uic.prf:
../qtsdk-2010.02/qt/mkspecs/features/yacc.prf:
../qtsdk-2010.02/qt/mkspecs/features/lex.prf:
../qtsdk-2010.02/qt/mkspecs/features/include_source_dir.prf:
/home/mik/qtsdk-2010.02/qt/lib/libQtWebKit.prl:
/home/mik/qtsdk-2010.02/qt/lib/libphonon.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtDBus.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtXml.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtCore.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtGui.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtXmlPatterns.prl:
/home/mik/qtsdk-2010.02/qt/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec ../qtsdk-2010.02/qt/mkspecs/linux-g++-64 -unix CONFIG+=debug -o Makefile MO.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/MO1.0.0 || $(MKDIR) .tmp/MO1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/MO1.0.0/ && $(COPY_FILE) --parents widget.h equation.h function.h inputWidget.h STable.h .tmp/MO1.0.0/ && $(COPY_FILE) --parents main.cpp widget.cpp equation.cpp function.cpp inputWidget.cpp STable.cpp .tmp/MO1.0.0/ && (cd `dirname .tmp/MO1.0.0` && $(TAR) MO1.0.0.tar MO1.0.0 && $(COMPRESS) MO1.0.0.tar) && $(MOVE) `dirname .tmp/MO1.0.0`/MO1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/MO1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_widget.cpp moc_equation.cpp moc_function.cpp moc_inputWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_widget.cpp moc_equation.cpp moc_function.cpp moc_inputWidget.cpp
moc_widget.cpp: inputWidget.h \
		equation.h \
		function.h \
		STable.h \
		widget.h
	/home/mik/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) widget.h -o moc_widget.cpp

moc_equation.cpp: equation.h
	/home/mik/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) equation.h -o moc_equation.cpp

moc_function.cpp: function.h
	/home/mik/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) function.h -o moc_function.cpp

moc_inputWidget.cpp: equation.h \
		function.h \
		inputWidget.h
	/home/mik/qtsdk-2010.02/qt/bin/moc $(DEFINES) $(INCPATH) inputWidget.h -o moc_inputWidget.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp widget.h \
		inputWidget.h \
		equation.h \
		function.h \
		STable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

widget.o: widget.cpp widget.h \
		inputWidget.h \
		equation.h \
		function.h \
		STable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o widget.o widget.cpp

equation.o: equation.cpp equation.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o equation.o equation.cpp

function.o: function.cpp function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o function.o function.cpp

inputWidget.o: inputWidget.cpp inputWidget.h \
		equation.h \
		function.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o inputWidget.o inputWidget.cpp

STable.o: STable.cpp STable.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o STable.o STable.cpp

moc_widget.o: moc_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_widget.o moc_widget.cpp

moc_equation.o: moc_equation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_equation.o moc_equation.cpp

moc_function.o: moc_function.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_function.o moc_function.cpp

moc_inputWidget.o: moc_inputWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_inputWidget.o moc_inputWidget.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

